name: spring-boot-admin
namespace: default

deployment:
  env:
    SERVER_SERVLET_CONTEXT_PATH: /spring-boot-admin
    SPRING_BOOT_ADMIN_UI_TITLE: Spring Boot Admin - Kubernetes
  image: spring-boot-admin
  # not recommended for production
  pullPolicy: Never
  updateStrategy: RollingUpdate
  maxSurge: 100%
  maxUnavailable: 0%
  replicas: 2
  restartPolicy: Always
  livenessProbe:
    initialDelaySeconds: 10
    timeoutSeconds: 10
  readinessProbe:
    initialDelaySeconds: 10
    timeoutSeconds: 10
