apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  strategy:
    type: {{ .Values.deployment.updateStrategy }}
    rollingUpdate:
      maxUnavailable: {{ .Values.deployment.maxUnavailable }}
      maxSurge: {{ .Values.deployment.maxSurge }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      restartPolicy: {{ .Values.deployment.restartPolicy }}
      terminationGracePeriodSeconds:  {{ .Values.deployment.terminationGracePeriodSeconds }}
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.deployment.image }}
        imagePullPolicy: {{ .Values.deployment.pullPolicy }}
        ports:
        - containerPort: 8080
          name: service
          protocol: TCP
        - containerPort: 8081
          name: management
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8081
          initialDelaySeconds: {{ .Values.deployment.livenessProbe.initialDelaySeconds }}
          timeoutSeconds: {{ .Values.deployment.livenessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.deployment.livenessProbe.successThreshold }}
          periodSeconds: {{ .Values.deployment.livenessProbe.periodSeconds }}
          failureThreshold: {{ .Values.deployment.livenessProbe.failureThreshold }}
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8081
          initialDelaySeconds: {{ .Values.deployment.readinessProbe.initialDelaySeconds }}
          timeoutSeconds: {{ .Values.deployment.readinessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.deployment.readinessProbe.successThreshold }}
          periodSeconds: {{ .Values.deployment.readinessProbe.periodSeconds }}
          failureThreshold: {{ .Values.deployment.readinessProbe.failureThreshold }}
