apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding-{{ .Values.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: role-{{ .Values.name }}
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Values.namespace }}
