server:
  port: 8080
spring:
  application: # Application-Infos for the Info-Actuator
    name: "@pom.artifactId@"
  # Spring Boot Admin
  boot:
    admin:
      ui:
        # public-url: http://localhost:8080
        title: Spring Boot Admin - Kubernetes
        brand: <img src="assets/img/icon-spring-boot-admin.svg"><span>Spring Boot Admin - Kubernetes</span>
      discovery: # Filter discovery to tagged services
        instances-metadata:
          spring-boot-admin: true
management: # Actuator Configuration
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint: # Health-Actuator
    health:
      show-details: always
      probes:
        enabled: true
    env: # Environment-Actuator
      show-values: always
    configprops: # Configuration-Actuator
      show-values: always
  info: # Info-Actuator
    java:
      enabled: true
    os:
      enabled: true
    build:
      enabled: true
    env:
      enabled: true
    git:
      enabled: true
info: # Application-Infos for the Info-Actuator
  group: "@pom.groupId@"
  artifact: "@pom.artifactId@"
  description: "@pom.description@"
  version: "@pom.version@"
  spring-boot: "@pom.parent.version@"
  spring-boot-admin: "@spring-boot-admin.version@"
  # Tags for the Spring Boot Admin UI
  tags:
    spring-boot: "@pom.parent.version@"
    spring-boot-admin: "@spring-boot-admin.version@"
logging: # Logging-File for the Logfile-Actuator
  file:
    name: "spring-boot-admin.log"
