server:
  port: 8080
spring:
  application: # Application-Infos for the Info-Actuator
    name: "@pom.artifactId@"
  boot:
    admin:
      ui:
        public-url: http://localhost:8080
        title: "Spring Boot Admin - Kubernetes"
      discovery:
        instances-metadata:
          spring-boot-admin: true
  cloud:
    kubernetes:
      discovery:
        enabled: true
        primary-port-name: service
management: # Actuator Configuration
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint: # Health-Actuator
    health:
      show-details: always
      probes:
        enabled: true
    env: # Environment-Actuator
      show-values: always
    configprops: # Configuration-Actuator
      show-values: always
  info: # Info-Actuator
    java:
      enabled: true
    os:
      enabled: true
    build:
      enabled: true
    env:
      enabled: true
    git:
      enabled: true
info: # Application-Infos for the Info-Actuator
  group: "@pom.groupId@"
  artifact: "@pom.artifactId@"
  description: "@pom.description@"
  version: "@pom.version@"
  spring-boot: "@pom.parent.version@"
  spring-boot-admin: "@spring-boot-admin.version@"
  tags:
    spring-boot: "@pom.parent.version@"
    spring-boot-admin: "@spring-boot-admin.version@"
logging: # Logging-File for the Logfile-Actuator
  file:
    name: "spring-boot-admin.log"
